"""empty message

Revision ID: 39f99b873a4c
Revises: 84e91bf3d654
Create Date: 2024-10-26 00:46:21.053871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39f99b873a4c'
down_revision = '84e91bf3d654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['post_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['forumuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['post_model.id'], name='answer_question_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['forumuser.id'], name='answer_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answer_pkey')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
