"""empty message

Revision ID: 657899ca23cb
Revises: 450e699f47e2
Create Date: 2024-10-24 17:48:41.047529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657899ca23cb'
down_revision = '450e699f47e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'forumuser', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
